version: '3'

services:
  mongo-write:
    container_name: mongo-write
    image: mongo
    volumes: 
      - ./data-write:/data/db

  mongo-read:
    container_name: mongo-read
    image: mongo
    volumes: 
      - ./data-read:/data/db