version: '3'

services:
  mongo-write:
    container_name: mongo-write
    image: mongo
    volumes: 
      - ./data-write:/data/db
      - ./scripts:/scripts
    links:
      - mongo-read
    ports:
      - 27017:27017
    command: bash -c "(./scripts/sync.sh&) ; mongod --bind_ip_all --replSet dbrs"

  
  mongo-read:
    container_name: mongo-read
    image: mongo
    volumes:
      - type: tmpfs
        target: /data/db
    ports:
      - 27018:27018
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--port", "27018"]
